buy_me_coffee/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf.urls.static import static
from django.conf import settings


urlpatterns = [
    path("admin/", admin.site.urls),

    # core
    path("", include('core.urls')),

    # user_profile
    path("auth/", include('user_profile.urls')),

    # creator
    path("creator/", include('creator.urls')),
] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

core/urls.py
from django.urls import path

from . import views


app_name = 'core'

urlpatterns = [
    # core
    path("", views.index, name='index'),
]

creator/urls.py
from django.urls import path

from . import views


app_name = 'creator'

urlpatterns = [
    # creator page
    path(
        'page/',
        views.creator_page,
        name='creator_page'
    ),

    # creators
    path(
        'creators/',
        views.creators,
        name='creators'
    ),

    # creator
    path(
        'creator/<int:pk>/',
        views.creator,
        name='creator'
    ),

    # edit creator
    path(
        'creator/edit/',
        views.edit_creator,
        name='creator_edit'
    ),
]

user_profile/urls.py
from django.urls import path
from django.contrib.auth import views as auth_views

from . import views


app_name = 'user_profile'

urlpatterns = [
    # login
    path(
        'login/',
        auth_views.LoginView.as_view(template_name='user_profile/login.html'),
        name='login'
    ),

    # signup
    path(
        'signup/',
        views.signup,
        name='signup'
    ),
]

creator/models.py
from django.db import models
from django.contrib.auth import get_user_model


User = get_user_model()


class Creator(models.Model):
    """
    Model to represent creators.
    """

    user = models.OneToOneField(User, related_name='creator', on_delete=models.CASCADE)

    title = models.CharField(max_length=255)
    description = models.TextField(null=True, blank=True)
    image = models.ImageField(upload_to='creator/creators/')

    created_at = models.DateTimeField(auto_now_add=True)

    def __str__(self) -> str:
        return self.title


class Support(models.Model):
    creator = models.ForeignKey(Creator, related_name='supports', on_delete=models.CASCADE)

    amount = models.IntegerField()
    is_paid = models.BooleanField(default=False)
    email = models.EmailField()
    cryptomus_uuid = models.UUIDField(blank=True, null=True)

    created_at = models.DateTimeField(auto_now_add=True)

    def __str__(self) -> str:
        return str(self.creator)

user_profile/models.py
from django.db import models

# Create your models here.

creator/forms.py
from django.forms import ModelForm

from .models import Creator


class CreatorForm(ModelForm):
    class Meta:
        model = Creator
        fields = (
            'title',
            'description',
            'image',
        )

core/views.py
from django.shortcuts import render


def index(request):
    return render(request, 'core/index.html')

creator/views.py
from django.shortcuts import render, redirect
from django.contrib.auth.decorators import login_required

from .models import Creator
from .forms import CreatorForm


def creators(request):
    creators = Creator.objects.all()

    return render(request, 'creator/creators.html', {
        'creators': creators
    })


def creator(request, pk):
    creator = Creator.objects.get(pk=pk)

    return render(request, 'creator/creator.html', {
        'creator': creator
    })


def edit_creator(request):
    try:
        creator = request.user.creator

        if request.method == 'POST':
            form = CreatorForm(request.POST, request.FILES, instance=creator)

            if form.is_valid():
                form.save()

                return redirect('core:index')
        else:
            form = CreatorForm(instance=creator)
    except Exception:
        if request.method == 'POST':
            form = CreatorForm(request.POST, request.FILES)

            if form.is_valid():
                creator = form.save(commit=False)
                creator.user = request.user
                creator.save()

                return redirect('core:index')
        else:
            form = CreatorForm()

    return render(request, 'creator/edit.html', {
        'form': form
    })


@login_required
def creator_page(request):
    creator = request.user.creator
    supports = creator.supports.filter(is_paid=True)
    total = 0

    for support in supports:
        total += support.amount

    return render(request, 'creator/creator_page.html', {
        'creator': creator,
        'supports': supports,
        'total': total
    })

user_profile/views.py
from django.contrib.auth.forms import UserCreationForm
from django.shortcuts import render, redirect


def signup(request):
    if request.method == 'POST':
        form = UserCreationForm(request.POST)

        if form.is_valid():
            form.save()

            return redirect('user_profile:login')
    else:
        form = UserCreationForm()

    return render(request, 'user_profile/signup.html', {
        'form': form
    })

core/templates/core/base.html
<!doctype html>

<html>
    <head>
        <meta charset="UTF-8">
        <meta name="viewport" content="width=device-width, initial-scale=1.0">
        <meta name="cryptomus" content="ede76745" />

        <script src="https://cdn.tailwindcss.com"></script>

        <title>{% block title %}{% endblock %} | Buy me a coffee</title>
    </head>

    <body class="bg-slate-700">
        <nav class="py-8 px-8 flex flex-row items-center justify-between bg-slate-900">
            <div>
                <a href="{% url 'core:index' %}" class="text-2xl text-white font-bold">Buy me a coffee</a>
            </div>

            <div class="space-x-6">
                <a href="{% url 'creator:creators' %}" class="py-4 px-6 text-lg font-bold text-white">Creators</a>

                {% if not request.user.is_authenticated %}
                    <a href="{% url 'user_profile:login' %}" class="py-4 px-6 text-lg font-bold text-white">Log in</a>
                    <a href="{% url 'user_profile:signup' %}" class="py-4 px-6 text-lg font-bold text-white bg-sky-800 rounded-lg">Sign up</a>
                {% endif %}

                {% if request.user.is_authenticated %}
                    <a href="{% url 'creator:creator_page' %}" class="py-4 px-6 text-lg font-bold text-white bg-sky-800 rounded-lg">My page</a>
                {% endif %}
            </div>
        </nav>

        <main class="py-6 px-8">
            {% block content %}
            {% endblock %}
        </main>

        <footer class="py-6 px-8 text-center bg-slate-600">
            <p class="text-slate-200">Copyright (c) 2024 - Buy me a coffee</p>
        </footer>

        {% block scripts %}
        {% endblock %}
    </body>
</html>

core/templates/core/index.html
{% extends 'core/base.html' %}

{% load static %}

{% block title %}Welcome{% endblock %}

{% block content %}
<div class="py-20 text-center space-y-12">
    <h1 class="text-7xl text-slate-300 font-bold">Get paid for your work</h1>

    <p class="text-xl text-slate-400">
        This is just some random information to show how it would look like with some actual content.
    </p>

    <a href="#" class="py-8 px-12 inline-block text-xl text-white bg-sky-800 rounded-lg">Create page</a>
</div>

<div class="py-12 bg-slate-800">
    <h2 class="mb-12 text-5xl text-slate-300 text-center font-bold">
        Coffee is love!
    </h2>

    <div class="flex justify-center items-center">
        <img src="{% static 'images/coffee.jpg' %}" alt="">
    </div>

    <div class="px-12 grid grid-cols-4 gap-8">
        {% for creator in creators %}
            <div class="bg-slate-600 rounded-lg">
                <figure>
                    <img src="#" class="rounded-tr-lg rounded-tl-lg">
                </figure>

                <div class="py-6 px-8 space-y-6">
                    <h3 class="text-xl text-slate-200 font-bold">Amin</h3>

                    <p class="text-slate-300">
                        Your friend!
                    </p>

                    <a href="#" class="py-4 px-6 inline-block text-xl text-white bg-sky-800 rounded-xl">Read more</a>
                </div>
            </div>
        {% endfor %}
    </div>
</div>
{% endblock %}

creator/templates/creator/creator.html
{% extends 'core/base.html' %}

{% load static %}

{% block title %}{{ creator.title }}{% endblock %}

{% block content %}
<div class="py-20 grid grid-cols-3 items-center">
    <figure class="col-span-1">
        <img src="{{ creator.image.url }}" class="rounded-lg">
    </figure>

    <div class="col-span-2 space-y-12 text-center">
        <h1 class="text-7xl text-slate-300 font-bold">{{ creator.title }}</h1>

        <p class="text-xl text-slate-400">
            {{ creator.description }}
        </p>
    </div>
</div>

<div class="py-12 bg-slate-800">
    <div class="px-12">
        <h2 class="mb-12 text-5xl text-slate-300 text-center font-bold">Support me</h2>

        <p class="text-xl text-slate-400 text-center">
            This is just some random infokajs dflja sldkfj alsk jdflkasjlkf jsalkdf
        </p>

        <div class="mt-12">
            <label>Your email address:</label><br>
            <input type="email" name="email" id="id_email">
        </div>

        <div class="mt-12 flex flex-row space-x-4 items-center justify-center">
            <a href="#" onclick="buy(1)" class="py-4 px-6 inline-block text-xl text-white bg-sky-800 rounded-lg">
                Buy me "1" coffee $1
            </a>

            <a href="#" onclick="buy(2)" class="py-4 px-6 inline-block text-xl text-white bg-sky-800 rounded-lg">
                Buy me "2" coffee $2
            </a>

            <a href="#" onclick="buy(5)" class="py-4 px-6 inline-block text-xl text-white bg-sky-800 rounded-lg">
                Buy me "5" coffee $5
            </a>
        </div>
    </div>
</div>

<form method="post" action=".">
    {% csrf_token %}

    <input type="hidden" id="creator_id" value="{{ creator.id }}">
</form>
{% endblock %}

{% block scripts %}
<script>
    console.log('Creator page');

    async function buy(amount) {
        console.log('Buy', amount);

        const csrftoken = document.querySelector('[name=csrfmiddlewaretoken]').value;
        const creatorId = document.getElementById('creator_id').value;
        const email = document.getElementById('id_email').value;

        const formData = new FormData();
        formData.append('email', email);
        formData.append('creator_id', creatorId);
        formData.append('amount', amount);

        const response = await fetch('/api/create_support/', {
            method: 'POST',
            headers: {
                'X-CSRFToken': csrftoken
            },
            body: formData
        });

        const data = await response.json();

        console.log('data:', data);

        window.location.href = data.url;
    }
</script>
{% endblock %}

creator/templates/creator/creator_page.html
{% extends 'core/base.html' %}

{% load static %}

{% block title %}{{ creator.title }}{% endblock %}

{% block content %}
<div class="py-20 grid grid-cols-3 items-center">
    <figure class="col-span-1">
        <img src="{{ creator.image.url }}" class="rounded-lg">
    </figure>

    <div class="col-span-2 space-y-12 text-center">
        <h1 class="text-7xl text-slate-300 font-bold">{{ creator.title }}</h1>

        <p class="text-xl text-slate-400">
            {{ creator.description }}
        </p>
    </div>
</div>

<div class="py-12 bg-slate-800">
    <div class="px-12">
        <h2 class="mb-12 text-5xl text-slate-300 text-center font-bold">My supporters</h2>

        <p class="text-xl text-slate-400 text-center">
            This is just some random infokajs dflja sldkfj alsk jdflkasjlkf jsalkdf
        </p>

        <div class="mt-12 text-center text-white space-y-5">
            {% for support in supports %}
                <p class="text-xl">{{ support.email }} - {% if support.amount == 1 %}One coffee{% elif support.amount == 2 %}Two coffee{% endif %} = ${{support.amount}} ({{ support.created_at }})</p>
            {% endfor %}

            <hr>

            <p class="text-xl font-bold">Total: ${{ total }}</p>
        </div>
    </div>
</div>
{% endblock %}

creator/templates/creator/creators.html
{% extends 'core/base.html' %}

{% load static %}

{% block title %}Creators{% endblock %}

{% block content %}
<div class="py-20 text-center space-y-12">
    <h1 class="text-7xl text-slate-300 font-bold">Creators</h1>
</div>

<div class="py-12 bg-slate-800">
    <div class="px-12 grid grid-cols-4 gap-8">
        {% for creator in creators %}
            <div class="bg-slate-600 rounded-lg">
                <figure>
                    <img src="{{ creator.image.url }}" class="rounded-tr-lg rounded-tl-lg">
                </figure>

                <div class="py-6 px-8 space-y-6">
                    <h3 class="text-xl text-slate-200 font-bold">{{ creator.title }}</h3>

                    <p class="text-slate-300">
                        {{ creator.description }}
                    </p>

                    <a href="{% url 'creator:creator' creator.pk %}" class="py-4 px-6 inline-block text-xl text-white bg-sky-800 rounded-xl">Read more</a>
                </div>
            </div>
        {% endfor %}
    </div>
</div>
{% endblock %}

creator/templates/creator/edit.html
{% extends 'core/base.html' %}

{% load static %}

{% block title %}Edit{% endblock %}

{% block content %}
<div class="py-20 text-center space-y-12">
    <h1 class="text-7xl text-slate-300 font-bold">Edit</h1>
</div>

<div class="py-12 bg-slate-800 text-blue-500">
    <form method="post" action="." enctype="multipart/form-data">
        {% csrf_token %}
        
        {{ form.as_p }}

        <div>
            <button class="w-full py-6 px-8 bg-sky-800 text-white font-bold rounded-lg">Submit</button>
        </div>
    </form>
</div>
{% endblock %}

user_profile/templates/user_profile/login.html
{% extends 'core/base.html' %}

{% load static %}

{% block title %}Log in {% endblock %}

{% block content %}
<div class="py-20 text-center">
    <h1 class="text-7xl text-slate-300 font-bold">Log in</h1>
</div>

<div class="max-w-lg mx-auto px-8 py-12 bg-slate-800">
    <form method="post" action="." class="space-y-6">
        {% csrf_token %}
        
        <div class="space-y-4">
            <label for="id_username" class="text-lg text-white">Username:</label>

            <input type="text" class="w-full py-6 px-8 bg-slate-600 text-white font-bold rounded-lg" name="username" autofocus="" autocapitalize="none" autocomplete="username" maxlength="150" required="" id="id_username">
        </div>

        <div class="space-y-4">
            <label for="id_password" class="text-lg text-white">Password:</label>

            <input type="password" class="w-full py-6 px-8 bg-slate-600 text-white font-bold rounded-lg" name="password" autocomplete="current-password" required="" id="id_password">
        </div>

        {% if form.errors %}
            <div class="py-6 px-8 bg-amber-600 text-white rounded-lg">
                <p>Username or password is not correct!</p>
            </div>
        {% endif %}

        <div>
            <button class="w-full py-6 px-8 bg-sky-800 text-white font-bold rounded-lg">Submit</button>
        </div>
    </form>
</div>
{% endblock %}

user_profile/templates/user_profile/signup.html
{% extends 'core/base.html' %}

{% load static %}

{% block title %}Sign up{% endblock %}

{% block content %}
<div class="py-20 text-center">
    <h1 class="text-7xl text-slate-300 font-bold">Sign up</h1>
</div>

<div class="max-w-lg mx-auto px-8 py-12 bg-slate-800">
    <form method="post" action="." class="space-y-6">
        {% csrf_token %}

        <div class="space-y-4">
            <label for="id_username" class="text-lg text-white">Username:</label>

            <input type="text" class="w-full py-6 px-8 bg-slate-600 text-white font-bold rounded-lg" name="username" autofocus="" autocapitalize="none" autocomplete="username" maxlength="150" required="" id="id_username">
        </div>

        <div class="space-y-4">
            <label for="id_password1" class="text-lg text-white">Password:</label>

            <input type="password" class="w-full py-6 px-8 bg-slate-600 text-white font-bold rounded-lg" name="password1" autocomplete="current-password" required="" id="id_password1">
        </div>

        <div class="space-y-4">
            <label for="id_password2" class="text-lg text-white">Repeat password:</label>

            <input type="password" class="w-full py-6 px-8 bg-slate-600 text-white font-bold rounded-lg" name="password2" autocomplete="current-password" required="" id="id_password2">
        </div>

        {% if form.errors %}
            <div class="py-6 px-8 bg-amber-600 text-white rounded-lg">
                <p>The username is already taken or there is something wrong with your passwords...</p>
            </div>
        {% endif %}

        <div>
            <button class="w-full py-6 px-8 bg-sky-800 text-white font-bold rounded-lg">Submit</button>
        </div>
    </form>
</div>
{% endblock %}